version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g typescript
      - npm ci
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '.ebextensions/*'
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'package.json'
  name: tcc-express-$(date +%Y-%m-%d)